### ISSUE TITLE
Spectron 13: waitUntilWindowLoaded is not a function

### ISSUE THREAD

**Issue by chinenual** [electron-userland/spectron#887]
I'm attempting to update my app to Electron 11.1.0 (so using Spectron ^13.0.0). My tests fail 
```
  1) Setup
       opens a window:
     TypeError: app.client.pause(...).waitUntilWindowLoaded is not a function
      at Context.<anonymous> (test/test.js:41:8)
      at processImmediate (internal/timers.js:458:21)
```
called via 
```javascript
it('opens a window', async () => {
    await app.client
      .pause(5000)
      .waitUntilWindowLoaded()
      .getWindowCount()
      .should.eventually.be.above(0)
      .getTitle().should.eventually.equal('MYAPP')

  });
```
This worked with Electron 8.2.5 and Spectron ^10.0.0. I have `chaiAsPromised.transferPromiseness = this.app.transferPromiseness` in my app startup.

This may be related to #656 ?   I see that webdriverio was updated (to v5 or v6? - #631) but can't see any reason that would break the Spectron client function `waitUntilWindowLoaded()`...?

Can anyone point me to a working example of Spectron testing an Electron 11.1.0 app?

**Comment by chinenual** [comment]
This is probably a breaking change in the webdriverio API (though I haven't found the mention in the changelogs).  FWIW, I've fixed by not chaining the calls:

```javascript
  it('opens a window', async () => {
    await app.client
      .pause(5000)
    await app.client
      .waitUntilWindowLoaded()
    await app.client
      .getWindowCount()
      .should.eventually.be.above(0)

    await app.client
      .getTitle().should.eventually.equal('MYAPP')

  });
```

Closing the issue, but leaving this solution in case it can help others.
