### ISSUE TITLE
this.app.client.waitUntilWindowLoaded(...).getWindowCount is not a function with electron 9.1

### ISSUE THREAD

**Issue by hovancik** [electron-userland/spectron#656]
Was working fine with electron 9.0.5. 

Same error for:

`TypeError: this.app.client.waitUntilWindowLoaded(...).windowByIndex is not a function`

SImple test as in readme: 

```
    return this.app.start()
      .then(() => {
        chaiAsPromised.transferPromiseness = this.app.transferPromiseness
        return this.app.client
          .waitUntilWindowLoaded()
          .getWindowCount()
          .should.eventually.be.at.least(1)
      })
```

**Comment by Himani33** [comment]
Any update on this issue, getting the same error on Electron: 9.2.1 and Spectron: 11.1.0

**Comment by nkj0305** [comment]
I have the same issue on Electron 9.2.0 and Spectron: 11.1.0. Is there any update on this?

**Comment by XRenSiu** [comment]
`this.app.client.waitUntilWindowLoaded()` return `Promise<void>`
```
await this.app.client.waitUntilWindowLoaded()
const windowCount = await this.app.cilent.getWindowCount()
```

**Comment by hovancik** [comment]
Not an expert here, but @XRenSiu , I think that that's taken care of by ` chaiAsPromised.transferPromiseness = this.app.transferPromiseness` 

It was working anyway fine with previous versions.

**Comment by daeteck** [comment]
I have the same problem. This issue was introduced in the version 11.1.0 and still persist in the version 12.0.0 (I was hopping to get fixed in version 12.0.0). 

Is like the promises are not getting transferred in chaiAsPromised.

What I saw is that this.app.cilent is a totally different object from version 11.0.0 to 11.1.0.

**Temporal fix for your issue:**
As you have ^11.0.0 in your package.json the npm install is installing the version 11.1.0 of spectron. What you can do in the meantime while this get fixed is remove the ^ in the version inside the package.json to force the npm to install the version 11.0.0

**Comment by KD0NKS** [comment]
Try this.  However, I have more playing to do before I get the window to close gracefully after a test is run.

```yaml
...
webPreferences: {
    enableRemoteModule: true, 
    nodeIntegration: true
}
...
```

**Comment by clai96** [comment]
Has this been fixed? I am running into it on Electron 10.1.6 and Spectron 12.0.0

**Comment by mafischer** [comment]
Still broken in Spectron 13..

**Comment by yoresu** [comment]
I am using electron 11.2.0 and spectrum 13.0.0 to test, but I also encounter this problem

**Comment by chinenual** [comment]
I'm attempting to update my app to Electron 11.1.0 (so using Spectron ^13.0.0).    Getting the same problem as above.

This worked with Electron 8.2.5 and Spectron ^10.0.0.   I have `chaiAsPromised.transferPromiseness = this.app.transferPromiseness` in my app startup.

**Comment by chinenual** [comment]
See my workaround/fix in #887 -- appears to be an API change in webdriverio -- functions that used to be chainable are no longer - need to call each one independently.

**Comment by yoresu** [comment]
await app.client.waitUntilWindowLoaded(15000)
 let count = await app.client.getWindowCount();
I try to get count successfully
