### ISSUE TITLE
unable to access element methods

### ISSUE THREAD

**Issue by wallage1216** [electron-userland/spectron#534]
i'm a new to spectron and software testing and run into the same issue over again.
we have an application build with electron 5.0.4, I'm writing GUI tests with cucumber-js / spectron 7.0.0. if i want to interact with GUI elements as coded below i get an error 

" TypeError: btn.click is not a function
           at Object.<anonymous> (D:\eldoled_sw_svn\dev\fluxtool-electron\e2e\features\step_definitions\Fluxtool_Compare_driver_vs_profile-steps.js:33:15)
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (internal/process/task_queues.js:93:5)"

`const btn = await app.client.element('.clear-compare')
    await btn.click()`

what does work is: 
`await app.client.element('.clear-compare').click()`

this works for me is some cases but not always.
Can someone tell me why the first code example doesn't work?

**Comment by PierreGuttAlive** [comment]
Just faced same behavior, bit of clarity would be nice

**Comment by wallage1216** [comment]
> Just faced same behavior, bit of clarity would be nice. Spectron 8.0.0, electron 6.0.10

I think I figured it out. Spectron is based on a rather old version of webdriver (spectron 10 is build on top of webdriver 4.13). A lot has changed in webdriver v5 was released.
