### ISSUE TITLE
app.client.click is not a function

### ISSUE THREAD

**Issue by jithin-zachariah** [electron-userland/spectron#709]
I am testing a simple electron app using Spectron. following is my test.js having a test case to click an element.
```
const Application = require('spectron').Application;
const assert = require('assert');
const electronPath = require('electron'); // Require Electron from the binaries included in node_modules.
const path = require('path');

describe('Application launch', function () {
  this.timeout(30000);

  beforeEach(function () {
    this.app = new Application({
      path: electronPath,
      args: [path.join(__dirname, '..')]
    });
    return this.app.start();
  });

  afterEach(function () {
    if (this.app && this.app.isRunning()) {
      return this.app.stop();
    }
  });

  it('shows an initial window', function () {
    return this.app.client.getWindowCount().then(function (count) {
      assert.equal(count, 1);
    });
  });

  it('Navigate to settings', async function () {
    return this.app.client.click('#settings').then(function (data) {
      console.log(data);
    });
  });
});

```
When I run mocha following is the output.
```
    √ shows an initial window
    1) Navigate to settings


  1 passing (45s)
  1 failing

  1) Application launch
       Navigate to settings:
     TypeError: this.app.client.click is not a function
      at Context.<anonymous> (test\test.js:30:28)
      at process._tickCallback (internal/process/next_tick.js:68:7)



npm ERR! Test failed.  See above for more details.
```

**Comment by XRenSiu** [comment]
`;(await app.client.$('#settings')).click()`

**Comment by jithin-zachariah** [comment]
```
  1) Application launch
       Navigate to settings:
     TypeError: this.app.client.$(...).click is not a function
      at Context.<anonymous> (test\test.js:32:8)
      at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by ZhengyiLuo** [comment]
it('Click', async() => {
            element = await app.client.$("#settings")
            await element.click()
        })

**Comment by berkon** [comment]
I'm having this issue as well (Electron 13.1.7 and Spectron 15.0.0). And I wonder how the example code of this book: https://livebook.manning.com/book/electron-in-action/chapter-13/73 could work at all. I would assume that the author tested it before publishing it. There are more code lines in that book which cause errors when trying them out. E.g. this one does not work as well:

`const title = await app.client.waitUntilWindowLoaded().getTitle();`

looks like `getTitle()` is not recognized as well. The only way to get it work was this way:

```
await app.client.waitUntilWindowLoaded()
const title = await app.browserWindow.getTitle()
```

**Comment by kennyish1173** [comment]
I am experiencing similar issues after updating Spectron from version 9.0 to 12.0.
Test scripts were working fine before the update.

sample `code:`
`it('should click Next button', function(){
	return app.client.windowByIndex(3).click(onBoardingPage.nextButton)
})`

error result:
`TypeError: app.client.windowByIndex(...).click is not a function`
