### ISSUE TITLE
Spectron 13 issues

### ISSUE THREAD

**Issue by c-handan-r** [electron-userland/spectron#825]
Hi,

After upgrading from spectron 7 to 13.0.0 
We are facing issues with the window handles.
Since our application contains multiple windows.

app.client.windowByIndex(). Is not returning the window handles.

Electron - 11.0.3
Spectron - 13.0.0

Code - 
Handle = app.client.windowByIndex(0)

Handle.execute('jquery').click()
Handle.$(xpath).click()

Error :
TypeError : Handle.execute()... Is not a function.
TypeError: Handle.$().. is not a function.

Any help is much appreciated.

**Comment by sowmyamurukutla** [comment]
I am also facing this issue, did you find any solution for this? with versions
 "electron": "^6.0.8"
"spectron": "^8.0.0"
 and our application has 3 windows
